### ISSUE TITLE
Experiments on Semantic Segmentation.

### ISSUE THREAD

**Issue by PkuRainBow** [fuy34/superpixel_fcn#1]
Dear authors,

Your work seems very **simple and effective** (compared to SSN) at grouping the pixels to superpixels and I am wondering whether you have tried it on the Cityscapes semantic segmentation track.
It would be great if you could share with me your conclusion or observation on the semantic segmentation tasks.

Besides, we are also wondering whether you could share the reproduced implementations of the other superpixel methods, e.g., SSN, to ensure the comparison under the fair settings.

Thanks!

**Comment by fuy34** [comment]
Hi, 
Thanks for your interest in our work.

We have not tried our method on the full CityScapes dataset, but we did apply to a part of it (~500 images, without fine-tuning) and the superpixel visualization pattern is similar to the ones on other datasets.  If you are interested in the quantitative curve,  please kindly follow the steps we did on NYUv2, It should not be hard to generate them, except it may require a great amount of the hard drive space to save all the results (including other methods'). 

For other methods, we either use the implementation on the [superpixel benchmark](https://github.com/davidstutz/superpixel-benchmark) or the public available code provided by the original authors. To reduplicate the results, you can simply follow their instructions. 

Thanks.
