### ISSUE TITLE
About inference

### ISSUE THREAD

**Issue by liuxy1103** [fuy34/superpixel_fcn#11]
The input size must be same as the patch size in training， or the performance will drop?

**Comment by fuy34** [comment]
Hi,  I am not sure what exactly you mean by the input size and path size. The precision, recall, and coherence score are sensitive to the number of superpixels, which will be affected by the grid size and the image size.  Please refer to the curves in the paper. Therefore, if you provide an image with a different size, the performance will be different.

**Comment by fuy34** [comment]
close due to the inactivity
