### ISSUE TITLE
training with custom datasets

### ISSUE THREAD

**Issue by ntaro0312** [fuy34/superpixel_fcn#12]
How can I train the model with my own dataset?

**Comment by fuy34** [comment]
Sure. You can modify the data loader to load your customized data.  This code only supports segmentation loss, which means you will need the color images and the ground truth segmentation (semantic segmentation, instance segmentation, etc.). But It should be fairly easy to modify the code to the color loss described in the paper. Then only color images are needed.

**Comment by euwern** [comment]
> Sure. You can modify the data loader to load your customized data. This code only supports segmentation loss, which means you will need the color images and the ground truth segmentation (semantic segmentation, instance segmentation, etc.). But It should be fairly easy to modify the code to the color loss described in the paper. Then only color images are needed.

Thanks, @fuy34, for sharing your code. How would you use color images as supervision? ("it should be easy to modify the code to the color loss described in the paper"). In the code, you use segmentation labels as supervision by converting the segmentation masks to one-hot labels followed by NN-interpolation. But how would you do this on color images without any segmentation masks? Do you first convert images to LAB using the "rgb2Lab_torch" function and then pass the output directly to the "compute_semantic_pos_loss" function?

**Comment by fuy34** [comment]
Yes, you can use the ```rgb2Lab_torch``` to convert the image to LAB space.

And for the color loss, you can modify the following code. It is slightly different from what I used in the stereo application, but the idea is the same. In that application, I rewrote it to better support multi-GPU training.  

```
def compute_color_loss(prob_in, labxy_feat, pos_weight = 10, multi_scale_weight=0, kernel_size=[16, 8, 4, 2]):
    # prob_in : B*9*H*W from the network output 
    # labxy_feat: B*5(LAB + XY)*H*W
    # this function support multi-scale output, but in our paper, we only use the final level output with kernel size 16. 

    S = kernel_size  # todo: currently we assume the downsize scale in x,y direction are always same
    m = pos_weight  # same m as the SLIC report http://www.kev-smith.com/papers/SLIC_Superpixels.pdf 
    loss_sum, loss_col_sum, loss_pos_sum = 0, 0, 0

    for i, prob in enumerate(prob_in): # if have multi-scale output, otherwise no need this loop 
        b, c, h, w = labxy_feat[i].shape
        pooled_labxy = poolfeat(labxy_feat[i], prob, kernel_size[i], kernel_size[i])
        reconstr_feat = upfeat(pooled_labxy, prob, kernel_size[i], kernel_size[i])

        loss_map = reconstr_feat - labxy_feat[i]

        loss_col = torch.norm(loss_map[:, :-2, :, :],p=2,dim=1).sum() / b
        loss_pos = torch.norm(loss_map[:,-2:,:,:],p=2,dim=1).sum() / b * m/ S[i]

        loss_sum += multi_scale_weight[i] * (loss_col + loss_pos) #weight[len(output)-1-i] *
        loss_col_sum +=  multi_scale_weight[i] * loss_col
        loss_pos_sum +=  multi_scale_weight[i] * loss_pos

    return loss_sum, loss_col_sum, loss_pos_sum
```
