### ISSUE TITLE
NameError: name 'enforce_connectivity' is not defined

### ISSUE THREAD

**Issue by nanersifang** [fuy34/superpixel_fcn#13]
Hello, I have a question here when run demo in my machine, can you help me please?

NameError: name 'enforce_connectivity' is not defined
File "/home/yangfq/PycharmProjects/pythonProject_sfcn/superpixel_fcn/train_util.py", line 243, in get_spixel_image
    spix_index_np = enforce_connectivity(spix_index_np[None, :, :], min_size, max_size)[0]
NameError: name 'enforce_connectivity' is not defined

I have already try different version of connectivity library.

How can I solve this problem, Thank you very much.

**Comment by fuy34** [comment]
Hi, 
Have you installed the Cython and enforce_connectivity module in ```third_party```? Please check ```Prerequisites``` for more details if have not.

**Comment by mcwoojcik** [comment]
Hello - I achieved the same error... I tried to install connectivity from your third_party/cython folder but. I had this output - maybe it causes the problem:
```
Compiling connectivity.pyx because it depends on /home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/__init__.pxd.
[1/1] Cythonizing connectivity.pyx
/home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/kaczor/superpixel_fcn/third_party/cython/connectivity.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
running build
running build_ext
building 'connectivity' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/core/include -I/home/kaczor/superpixel_fcn_env/include -I/usr/include/python3.8 -c connectivity.c -o build/temp.linux-x86_64-3.8/connectivity.o
In file included from /home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944,
                 from /home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from connectivity.c:627:
/home/kaczor/superpixel_fcn_env/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/connectivity.o -o build/lib.linux-x86_64-3.8/connectivity.cpython-38-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.8/connectivity.cpython-38-x86_64-linux-gnu.so -> /home/kaczor/.local/lib/python3.8/site-packages
running install_egg_info
Removing /home/kaczor/.local/lib/python3.8/site-packages/Connectivity-0.0.0.egg-info
Writing /home/kaczor/.local/lib/python3.8/site-packages/Connectivity-0.0.0.egg-info
```

Packages info:
```
cycler==0.10.0
Cython==0.29.23
decorator==4.4.2
imageio==2.9.0
kiwisolver==1.3.1
matplotlib==3.4.1
networkx==2.5.1
numpy==1.20.2
opencv-python==4.5.1.48
Pillow==8.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.18.1
scipy==1.6.2
six==1.15.0
tifffile==2021.4.8
torch==1.8.1
torchaudio==0.8.1
torchvision==0.9.1
typing-extensions==3.7.4.3
```
System info:
```
Linux Ubuntu 20.04
GPU - RTX 3080 Laptop
CPU - AMD Ryzen 7 5800H
```
Run under virtualenv

**Comment by fuy34** [comment]
I see.  I have never tried to run the code with your environment setting. 

Could you try to install a virtual environment with python 2.7 and torch 0.4.1?  I developed the code with this setting. There might be some version conflicts as the package updates. You can try torch with CPU version first if the 3080 GPU does not support the old pytorch version. The speed should still be acceptable for the demo running. 

I have successfully run everything on python 3.6 and torch 1.2 before. But the cython was installed through conda. I hope it helps.

**Comment by nanersifang** [comment]
Yes , finally I check 

> Hi,
> Have you installed the Cython and enforce_connectivity module in `third_party`? Please check `Prerequisites` for more details if have not.

Thank you very much. Yes , in third_party folder , I run python setup.py build_ext --inplace , and then it works, I do run with cpu first.

**Comment by Maypku** [comment]
Change the line "from connectivity import enforce_connectivity" to "from skimage.segmentation._slic import _enforce_label_connectivity_cython" in train_util.py, in that can debug the ‘run_demo.py’ and 'main.pu' with GPU in Python 3.7
