### ISSUE TITLE
Why are there many isolated regions with identical IDs

### ISSUE THREAD

**Issue by liuxy1103** [fuy34/superpixel_fcn#14]
Why are there many isolated regions with identical IDs. The pixels assigned to identical  superpixel is not together.

**Comment by fuy34** [comment]
Have you enabled the  ```enforce_connectivity```?  Something like https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/run_infer_bsds.py#L102

Our model does not enforce the connectivity during either training or test time. Therefore, if you run our plain model, it could happen.
