### ISSUE TITLE
What does  the unique map mean?

### ISSUE THREAD

**Issue by Juvexyy** [fuy34/superpixel_fcn#17]
When I run run_demo.py, it generates the unique maps as csv file, what does this file represent?

**Comment by fuy34** [comment]
Hi,

Sorry for the late reply. Could you tell me more about the csv file?

I believe I have commented the following lines. And normally, you should get csv file from run_demo.py
https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/run_demo.py#L123 

The csv file we generate in run_infer_**.py is for evaluation purposes. The [Superpixel Benchmark](https://github.com/davidstutz/superpixel-benchmark/blob/master/docs/DATASETS.md) takes csv files in their evaluation code.
