### ISSUE TITLE
why the results looks mosaic

### ISSUE THREAD

**Issue by liuxy1103** [fuy34/superpixel_fcn#21]
![image](https://user-images.githubusercontent.com/54794058/122644727-52637680-d149-11eb-8a64-0fdb7efd8c57.png)

**Comment by fuy34** [comment]
Hi, 
Could you provide more details about this? It is hard to guess what happens with the image you show.

**Comment by liuxy1103** [comment]
The resulting superpixels appear in a regular grid shape

**Comment by liuxy1103** [comment]
![image](https://user-images.githubusercontent.com/54794058/122658921-0f36f100-d1a5-11eb-8cd8-8bc1b78b64e6.png)

**Comment by fuy34** [comment]
Ok, so are you using the default setting, saying BSDS500 dataset + all default parameters for training? 

How does training look like? Did this happen at training time or test time? 

Did you enable the ```enforce_connectivity```
https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/run_demo.py#L18

Without detailed information, I cannot tell what exactly happens to your model.

**Comment by liuxy1103** [comment]
I didn't use the BSDS500, I used a biomedical dataset to train and test the model. I find that the regular grid appears inside the objects and the  boundaries between different objects can be adjusted to be adhered

**Comment by fuy34** [comment]
I see. It is hard to tell what happens. 
How about training with our default setting first? Just to make sure your environment setting is correct. 
If you can reproduce our result, but fail to apply it to your data, we can discuss it from there.

**Comment by BJHYZJ** [comment]
> ![image](https://user-images.githubusercontent.com/54794058/122658921-0f36f100-d1a5-11eb-8cd8-8bc1b78b64e6.png)
Hello, in fact, I have also encountered a lot of QR codes like you, but after more iterations, these rectangles gradually expand around and become irregular. I don't know if this is normal. Phenomenon. Would like to ask if you have solved this problem or if you found out what the problem is.
