### ISSUE TITLE
Convergence criteria

### ISSUE THREAD

**Issue by jibrilmuhammadadam** [fuy34/superpixel_fcn#23]
Hi, 
Thank you for making your work available. In the paper it was stated that "Convergence is reached at about 300k iterations." under "Implementation details" in section "3.4. Experiments". What is the criteria you used to determine the convergence? Thanks once again.

**Comment by fuy34** [comment]
Hi, 
Thank you for your interest in our work. By saying convergence, we basically meant the validation loss does not decrease (at least any significantly) anymore. A reasonable segmentation usually appears after tens of epochs BTW. :)

**Comment by jibrilmuhammadadam** [comment]
Thanks for the prompt response. I am trying to implement the concept in a 3D setting and the semantic loss is initially very high as in your work. Did your semantic loss reach less than 1?

**Comment by fuy34** [comment]
Actually, I cannot remember the exact loss value. I did this project about 2 years ago (in 2019). 

I do not have an impression of abnormally high loss. One thing worth noting is that our code currently only supports ```downsize``` that is dividable to the image/volume resolution (issue #19). It may not relate to what you are suffering, but just in case, it will help.

**Comment by jibrilmuhammadadam** [comment]
Noted. Thank you.
