### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by youyeg** [fuy34/superpixel_fcn#24]
Could you please include the requirments.txt?
It had some problems with opencv and I'm not sure what are the versions of the libraries you used.
It's also appreciated if you could include python 3 version. 2to3 didn't work for me, and I'm not sure it was due to the requirements version or not.

**Comment by fuy34** [comment]
Hi @youyeg 
I installed packages in a conda environment. I have removed it now, and so cannot provide a dependency list. Sorry about it.
I would suggest just install anaconda, and do ```conda create -n spixelFCN python=2.7```. After that,  just ```conda or pip install``` any package that is reported is missing. I did not aware of any dependency issue. It should work directly.
