### ISSUE TITLE
Hello, may I ask how to adjust the number of super pixels?

### ISSUE THREAD

**Issue by hetiansheng123** [fuy34/superpixel_fcn#28]
Hello, may I ask how to adjust the number of super pixels?

**Comment by fuy34** [comment]
Hi, please take a look at issue #27, and please let me know if you have any further questions.

**Comment by hetiansheng123** [comment]
Thank you very much for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuy34/superpixel_fcn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuy34/superpixel_fcn] Hello, may I ask how to adjust the number of super pixels? (#28)





 
Hi, please take a look at issue #27, and please let me know if you have any further questions.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
