### ISSUE TITLE
Trying to understand the SP-PSMNet implementation better

### ISSUE THREAD

**Issue by mszuyx** [fuy34/superpixel_fcn#31]
Our team is trying to merge SpixelNet with our task network as well to improve the segmentation boundary accuracy. We do believe this will greatly push the performance of the task network further! However, as we followed your supplement material, we have some confusions:
![Screenshot 2021-12-15 15:22:48](https://user-images.githubusercontent.com/37651144/146269518-eb7d47f3-af60-46c7-a214-1842a8a63c04.png)

1. There is a layer called "**sImg_1/2**" using the kernel named "**assoc_1/2**" and stride 4 to down sample the association map that output by SpixelNet (the H x W x 9 tensor) to (1/4 H x 1/4 W x 3). This of course makes sense since most of the backbone / task network only take 3 channel input (RGB images). So in order to merge the two models, we need to massage the output of SpixelNet to some 3 channel tensors. So, if I understand this correctly, this "**sImg_1/2**" is a custom conv2d layer that doesn't belong to SpixelNet nor PSMNet? If so, does it require any special initialization / activation? (Also I'm guessing the "1/2" denotes left/right image?)
2. Furthermore, when you mentioned in the paper: "_replace the conventional operations for downsampling (e.g., stride-2 convolutions) and upsampling (e.g., bilinear upsampling) in the task network with a superpixel-based ownsampling/upsampling scheme to effectively preserve object boundaries and fine details._" What operations did you use for the "upsampling"? Judging by the supplement material, it seems like a concatenation between the upsampled output from the PSMNet and the association map "**assoc_1**" (the H x W x 9 tensor? Yet it is marked H x W x D) along dimension one, and maybe followed by some conv2d to make sure the tensor shape satisfies the input shape of the disparity regression module? And why the "**assoc_1**" has stride 4?

It will be really helpful if we can get some input from you directly! Thanks! :  )

**Comment by fuy34** [comment]
Hey @mszuyx ,
Thank you for your interest, and apology for the confusing annotation in the paper. 

For your first question,  ```sImg_1/2``` means the images downsampled with our SpixelNet, where ```assoc_1/2``` indicates the association map for superpixel downsampling given the two images ```Img_1/2``` as input. 

For the second question, we use 4*4 grid for SpixelNet in this experiment. Therefore, the image will be downsampled 4 times. 

Hope this helps.

**Comment by mszuyx** [comment]
@fuy34 Thank you for your quick response!

I thought Table.1 is the entirety of the SpixelNet, no?

1. The default setting from Table.1 has an output with the shape H x W x 9, which matches with Table.2. That leads me to think that this layer called "sImg_1/2" using the kernel named "assoc_1/2" is a conv2d layer. Because as Table.1 suggests, SpixelNet doesn't change the spatial size of its output, so some additional operations are required to downsample the output from SpixelNet and **also change the channel size to 3**.  (**H x W x 9**  to **1/4 H x 1/4 W x 3**)
2. Lastly, I am still confused with what operations were taken to upsample the output of PSMNet before its disparity regression. The "superpixel-based upsampling" section has two lines per row, what does the "OutDim" mean in this case?
3. In #6, you mentioned:
> (2) up-sample the output cost volume with feature function in our repo 

What is "feature function" referring to? Is it "assoc_1"? The association map of the left image?

Thanks!

**Comment by fuy34** [comment]
Yes, Table 1 shows the network architecture of SpixelNet. 

In our stereo experiment, we use a 4 x 4 grid, but it does not affect the resolution of ```assoc_1/2```. The association map indicates the pixel association to superpixel (or the center of the grid cell).  The only impact of this 4 x 4 setting is the size of the generated superpixel.  For more information, please refer to Sec. 3.2 in our paper, including how the downsampling  (Eq. 1) and upsampling (Eq. 2) happen. 

There are two ways to upsample the disparity map, we can do either before the weight regression or after it. Please check the code of PSMNet, we essentially replace its bilinear upsampling with our superpixel upsampling. The first way will lead to slightly higher accuracy but require more GPU memory. Therefore, we choose the second way in our paper. 

For upsampling function, you can use this one. 
https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/train_util.py#L130

**Comment by mszuyx** [comment]
I see. It's much clearer now!

So the feature function "`upfeat`" takes in the "downsampled feature vector with N channels" as well as the "association map with 9 channels" to perform the upsampling scheme according to Eq(2). The arguments "`up_h`" and "`up_w`" are the scaling factors I assume?
I will try to implement it ASAP and I will let you know how it goes!

Last few things:
>  sImg_1/2 means the images downsampled with our SpixelNet

1. Does it mean "sImg_1/2" is a skip connection coming out from somewhere in Tabel.1? 
2. And what is the purpose of `def poolfeat(input, prob, sp_h=2, sp_w=2)`?

**Comment by fuy34** [comment]
Yes, your understanding is correct. 

As I mentioned above,  ```sImg_1/2``` is the output from SpixelNet. Essentially, we use SpixelNet to downsample ```Img_1/2``` to ```sImg_1/2``` and take the later one as input for the modified PSMNet.  Please check Sec. 4 and Fig. 1 in the paper for the details. The ```poolfeat``` function can be used for the downsampling.

**Comment by fuy34** [comment]
H

**Comment by mszuyx** [comment]
Hi @fuy34 , sorry for the delay. I hope you are doing well!

As I actually implement the code, I realize there is still much for me to learn from your work, and I could really use your help to clear one more confusion (about how to obtain **sImg_1/2**):

> As I mentioned above, **sImg_1/2** is the output from SpixelNet. Essentially, we use SpixelNet to downsample **Img_1/2** to **sImg_1/2** and take the later one as input for the modified PSMNet. 

In my understanding, the only output of the SpixelNet is the **assoc_1/2** (a.k.a association map or Q, with shape H x W x 9), so I am a little confused why **sImg_1/2**  is considered as an output. 
It seems, to obtain **sImg_1/2** (a.k.a the center map or down-sampled images), **assoc_1/2** is required in Eq(1)(2). -- But the closest thing I can find is the **update_spixl_map()** function, as it takes "spixeIds" and **assoc_1/2** to generate a human readable H x W x 1 super pixel map. And for the purpose of getting "super pixels", this is all we need.

1. However, I am not sure how to obtain **sImg_1/2** from here. As **sImg_1/2** is a H x W x 3 image, which scaling is determined by the grid cell size (the '--downsize' argument) of the SpixelNet. I wonder what am I missing here. I thought there is a corresponding function that takes **Img_1/2** and **assoc_1/2** as inputs and outputs **sImg_1/2** at the end. -- But I couldn't find any. So, I assume I must got something wrong here?
2. If we would like a different down-sampling scale (grid cell size), I assume we need to retain the model ourselves, correct?

Thank you for your support!
Yu
