### ISSUE TITLE
How to set the mean and std when i want to change the training set?

### ISSUE THREAD

**Issue by Surrin1999** [fuy34/superpixel_fcn#32]
Hello, thanks to your nice work.

I am trying to improve your work. When I need to train your model on different dataset, how should the mean and std in the input_transform be adjusted? Or should it remain the same?
![image](https://user-images.githubusercontent.com/37960540/155935852-d35a9e64-938c-477c-904f-ee1bb4344e67.png)

**Comment by Surrin1999** [comment]
The second mean and standard deviation **(mean = [0.411,0.432,0.45], STD = [1,1,1]**), I initially thought it was set according to the mean and std of BSDS500 training set, but after calculation, I found it was not.

How is this set?

**Comment by fuy34** [comment]
Hey, I think you can set the mean and std of BSDS5000 as well. 

This number will not affect the final result a lot. I directly copied the current value from the [FlowNetPyTorch](
https://github.com/ClementPinard/FlowNetPytorch/blob/master/main.py) repo.

**Comment by Surrin1999** [comment]
> 

Thank you!😁
