### ISSUE TITLE
train for rgb or lab？

### ISSUE THREAD

**Issue by Cherished-l** [fuy34/superpixel_fcn#33]
Hi
I find the image maybe is trained in rgb， not for lab？ it's sure?
could you tell me which should i take, rgb or lab, to train?

**Comment by Cherished-l** [comment]
in other words, i don't find the inputs converted to lab for network training, so if i use custom dataset, should i use lab or rgb to train？

**Comment by Cherished-l** [comment]
in other words, i don't find the inputs converted to lab for network training, so if i use custom dataset, should i use lab or rgb to train？ or maybe rgb for input，lab for cmpute loss?
Looking forward to your reply

**Comment by fuy34** [comment]
Hi, 

We always use RGB images as inputs to the network.  If you want to train with color loss, just changing the image to LAB format for the loss calculation is enough.

**Comment by Cherished-l** [comment]
Thanks
if i use rgb2lab_torch, the parameter 'mean' should be the mean of the datasets, which is used in transforms.normalize?

**Comment by Cherished-l** [comment]
Thank you very much
