### ISSUE TITLE
About slic_loss

### ISSUE THREAD

**Issue by BanaBanaBanaa** [fuy34/superpixel_fcn#34]
Hi! Thanks for your share.
When I use my own dataset, I met the problem : "local variable ' slic_loss' referenced before assignment", but when I use BSD500 to train I didn't meet this problem. Can u know this is why?
Thanks for your patiance!

**Comment by fuy34** [comment]
I do not think we use ```slic_loss``` in this repo. Do you mean the one here https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/main.py#L272
which is actually the sum of ```loss_sem``` and ```loss_pos```?
Could you provide more details?

**Comment by BanaBanaBanaa** [comment]
ok! 
I will attach a screenshot。
![image](https://user-images.githubusercontent.com/103991977/164362330-c608d3e3-b2a5-42cb-ae01-38b25cda3019.png)

**Comment by fuy34** [comment]
Please excuse me, I am a little confused.  Do you mean the ```label``` is not defined? 
I have defined at dataloader part 
https://github.com/fuy34/superpixel_fcn/blob/0f07be910e41ac73404de23caa99f0e454c6440c/main.py#L251

**Comment by BanaBanaBanaa** [comment]
I‘m sorry about this.
The background color marked with yellow has this problem, but this variable has also appeared before, which I was also confused.

**Comment by fuy34** [comment]
I see. 

My guess is these are just warnings from IDE, even though I do not know the reason. If you can run the program without errors, I think it is probably fine to ignore them.

**Comment by BanaBanaBanaa** [comment]
When i use my dataset, it met the error when running the program but have nothing to run the program whtn use BSD500.
Whatever thanks for your patience !

**Comment by fuy34** [comment]
May I ask what errors you met with your own dataset? If it is the same, you may want to check if you have pre-defined the corresponding variables in your code. Hope you can figure it out soon. :)

**Comment by BanaBanaBanaa** [comment]
The mistake is as follows: 
File "train.py", line 314 in train: train_writer.add_scalar('Train_loss_epoch', slic_loss.item(),epoch) 
UnboundLocalError: local variable 'slic_loss' referenced before assignment.

**Comment by fuy34** [comment]
This is abnormal because this is not the first place where ```slic_loss``` appears. 

My guess is the ```for``` loop for the data loading and training is not working. In other words, your dataloader is given an empty list. Could you check if you have implemented your customized dataset correctly?

**Comment by BanaBanaBanaa** [comment]
Thank u！
I will check my dataset.

**Comment by BanaBanaBanaa** [comment]
I have checked my dataloader, it really had some mistakes!
Thank u very much !

**Comment by fuy34** [comment]
That is great! Gald you worked it out!
