### ISSUE TITLE
About the downstream task

### ISSUE THREAD

**Issue by BanaBanaBanaa** [fuy34/superpixel_fcn#35]
Hi！ 
Thanks for open-sourcing this awesome work.
I have some questions about how to use to train the downstream task?
I noticed that you said in the essay that you develop a downsampling/upsampling scheme for deep networks with the goal of generating high-resolution outputs for dense prediction tasks. Can you share with me about the job? Or can you give me some ideas about how to do?
I'll appreciate it if you replied to me! Thanks!

**Comment by fuy34** [comment]
Please check this [repo.](https://github.com/fuy34/SPPSMStereo) for the stereo matching application. I have not got time to write the readme. It is essentially the same setting as we described in the paper.

**Comment by BanaBanaBanaa** [comment]
Thank u!
I will refer to the repo SPPSMStereo!
