### ISSUE TITLE
Cuda9.0

### ISSUE THREAD

**Issue by ShamsaHasnain** [fuy34/superpixel_fcn#37]
Hy! 
I'm student of research. I'm interested in your code of Superpixel_fcn and I like it strongly.
I want to use this code in own research era.

During installation of cuda 9 , occur errors " graphic driver not compatible with this version of windows ". How I solve it... 
In your code which GPu have used for cuda 9.

I have some troubles to install cuda 9. Please help me for solve my problem....

**Comment by fuy34** [comment]
Hi, 

Thank you for your interest. I used 1080Ti GPU for this project. I guess you have a more advanced GPU that no longer supports CUDA 9.0. You can go whatever CUDA version your GPU is compatible with, and then install the corresponding PyTorch version.  The performance may be various a little bit, but the code should work in general. 

Thanks.

**Comment by ShamsaHasnain** [comment]
Thank you for your reply!
