### ISSUE TITLE
A rectangular grid appears in the test results

### ISSUE THREAD

**Issue by BJHYZJ** [fuy34/superpixel_fcn#38]
Hello author, thank you for your contribution. I retrained after modifying the model architecture, but the matrix grid appeared in the results during the test, which seemed to be initialized superpixels. I don’t know if this is normal.
![206097_img_sPixel](https://user-images.githubusercontent.com/74347732/179335811-ee52b25f-40c3-41a7-94ad-dd75987949f8.png)

**Comment by fuy34** [comment]
Well, what is the training looks like? And could you check this image with our pre-trained model? Personally, I believe our model can perform better than this.

**Comment by BJHYZJ** [comment]
Yes, you are working really well, I used this image because I wanted to show you the problem with squares, I recently discovered that the initialization of a superpixel is to split the image into regular rectangles, and then with With increasing iterations, these rectangles will gradually deform into random superpixel blocks. So I want to ask you, is this normal?

**Comment by BJHYZJ** [comment]
![image](https://user-images.githubusercontent.com/74347732/179439576-6fdf1d6d-6ed5-4241-8a5a-255f3e09f17e.png)
like this

**Comment by fuy34** [comment]
The training looks not right to me. Hope you have solved the problem, as you closed the issue. :)
