### ISSUE TITLE
I want to know about the formula of upfeat and poolfeat.

### ISSUE THREAD

**Issue by JimmyMa99** [fuy34/superpixel_fcn#39]
Hello, I don't know how to write upfeat and poolfeat pixel formula, can you provide me the pixel formula for upfeat and poolfeat image using Q?

**Comment by JimmyMa99** [comment]
And I use Q poolfeat+upfeat to process raw images, here is an example.
![2007_009245](https://user-images.githubusercontent.com/101508488/196477049-5f745e28-6bc1-4574-a67d-ce88ba8d0f06.jpg)
![微信图片_20221017105929](https://user-images.githubusercontent.com/101508488/196477081-8b3402da-a97f-404e-bf50-c8296a6f564b.jpg)
![微信图片_20221017111905](https://user-images.githubusercontent.com/101508488/196477121-85dba6d1-fc62-4d1d-abdd-8b54e533c9b4.jpg)

Can I consider your f(p) in equation 1 in the paper as the first graph and f'(p) in equation 2 as the last graph?

**Comment by JimmyMa99** [comment]
Can I assume that the us in equation 1 is the result of poolfeat? Is f'(p) in equation 2 the result of upfeat?

**Comment by fuy34** [comment]
Hi, you are right. The ```poolfeat``` is corresponding to Eq.1, and Eq.2 is corresponding to ```upfeat```.

**Comment by JimmyMa99** [comment]
Thanks.
