### ISSUE TITLE
Why is the downsize 16?

### ISSUE THREAD

**Issue by daimaohui** [fuy34/superpixel_fcn#40]
![图片](https://user-images.githubusercontent.com/54748105/211182238-439b9fa7-7a2a-4be5-aa49-9fe2cf7d6135.png)
![图片](https://user-images.githubusercontent.com/54748105/211182257-d38c1979-344f-4594-8a5c-f4dd60caba0d.png)

Can we set the downsize to 32?

What's the difference between 32 * 32 and 16 * 16？

![图片](https://user-images.githubusercontent.com/54748105/211182309-9f4dd979-0b3e-4625-a1ac-b176d140ab2f.png)

run_demo.py   superpixel grid cell, must be same as training setting why?

Can we use 16 * 16 training 32 * 32 to predict?

**Comment by fuy34** [comment]
Hi, Thanks for your interest in our work. You can do 32 for sure. We use 16 just for a better trade-off between speed and performance.

if you wish to use 32*32, you probably need to retrain the network, as the provided checkpoint are trained with 16*16.

**Comment by daimaohui** [comment]
Can we use 16 * 16 training，32 * 32 to predict?

**Comment by daimaohui** [comment]
In my own dataset, I use 16 * 16 for training and 16 * 16 for testing, and the final BP is 0.75. But I use 16 * 16 for training and 32 * 32 for testing, and the final BP is 0.88. However, I use 32 * 32 for training and 32 * 32 for testing, and the final BP is 0.44. All parameters of the three experiments are the same. So is it correct to use 16 * 16 for training and 32 * 32 for testing?

**Comment by fuy34** [comment]
This is interesting. We never tried to test with a different size than the training setting. I, personally, believe it is weird. Could you share some visualization? Also, how are the BR and other metrics? Looking into BP alone may cannot provide sufficient signals to study what is going on.
