### ISSUE TITLE
raise RuntimeError('Attempting to deserialize object on a CUDA

### ISSUE THREAD

**Issue by Adnan1986** [fuy34/superpixel_fcn#41]
Hi,

Thank you for sharing your works. I have tried to run your code in (cuda 9.1, pytorch 1.4, conda environment on windows).
When runing the demo I got following error, while I am using cuda device and return TRUE in python. Is there a way to fix it?

![image](https://user-images.githubusercontent.com/53436210/217614839-f18be022-abb4-4a5a-a808-e01dc22bf101.png)

Thanks

**Comment by fuy34** [comment]
Hi, Thank you for your interest in our work. 

I do not have a windows machine to reproduce this issue. Have you tried it on a Linux machine? 

A few possible ways to fix this:
1. set ```os.environ['CUDA_VISIBLE_DEVICES'] = '0'``` if you only have one GPU on the machine https://github.com/fuy34/superpixel_fcn/blob/ae81e171a64dc9ed26a039a1a52b87b5fe744cf1/run_demo.py#L35
2. change all ```.cuda()``` to ```.cpu()``` in the .py file 
3. install the Linux environment using WSL on windows 

Hope it helps.

**Comment by Adnan1986** [comment]
> Hi, Thank you for your interest in our work.
> 
> I do not have a windows machine to reproduce this issue. Have you tried it on a Linux machine?
> 
> A few possible ways to fix this:
> 
> 1. set `os.environ['CUDA_VISIBLE_DEVICES'] = '0'` if you only have one GPU on the machine https://github.com/fuy34/superpixel_fcn/blob/ae81e171a64dc9ed26a039a1a52b87b5fe744cf1/run_demo.py#L35
> 2. change all `.cuda()` to `.cpu()` in the .py file
> 3. install the Linux environment using WSL on windows
> 
> Hope it helps.

Thank you. Your 1st solution have worked.

Just one more things, how many epochs are sufficient for training. I am going to use your result for comparison with other algorithms, so I want to  have a fair comparison. In additions, since to install cuda 9, I have used an old gpu, so training could take much time and 300K as a default could be a lot
