### ISSUE TITLE
ERROR:'../SPixelNet_nSpixel_864/map_csv: is a directory' when execute 'bash my_eval.sh'

### ISSUE THREAD

**Issue by zxcvbml** [fuy34/superpixel_fcn#43]
**When I evaluate my predicted results, I got a error as follows,, I don't know the reason. Hoping your response. Thank you very much.**

```
ruby@ruby-MS-7D36:~/code/superpixel-benchmark/examples$ bash bash/my_eval.sh 
54
bash/my_eval.sh: 行 43: /home/ruby/code/AINET/output/test_multiscale_enforce_connect/SPixelNet_nSpixel_54/map_csv: 是一个目录
```

**the settings in the my_eval.sh as follows:**

```
SUPERPIXELS=("54" "96" "150" "216" "294" "384" "486" "600" "726" "864" "1014" "1176" "1350" "1536" "1944") #

#SUPERPIXELS=("293" "1175") #
IMG_PATH=/home/ruby/code/AINET/test
GT_PATH=/home/ruby/code/AINET/test/map_csv

for SUPERPIXEL in "${SUPERPIXELS[@]}"
do
echo $SUPERPIXEL
/home/ruby/code/AINET/output/test_multiscale_enforce_connect/SPixelNet_nSpixel_${SUPERPIXEL}/map_csv $IMG_PATH $GT_PATH

done
```

**the directory of ‘map_csv‘ as follows：**
100007_img.csv
100039_img.csv
...

**Comment by fuy34** [comment]
From the error message, it seems the binary file is not well generated or set up. Could you double-check that?

**Comment by zxcvbml** [comment]
Yes,&nbsp;I have already resolved it by set the binarg file, thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuy34/superpixel_fcn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuy34/superpixel_fcn] ERROR:'../SPixelNet_nSpixel_864/map_csv: is a directory' when execute 'bash my_eval.sh' (Issue #43)





 
From the error message, it seems the binary file is not well generated or set up. Could you double-check that?

**Comment by fuy34** [comment]
Glad it works now!
