### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by Joazs** [fuy34/superpixel_fcn#45]
I run the run_demo.py. Then,

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

But my torch.cuda.is_acailable() is True.

What's wrong?

**Comment by Aliyadodo** [comment]
os.environ['CUDA_VISIBLE_DEVICES'] = '1' chaned to '0'

**Comment by fuy34** [comment]
> os.environ['CUDA_VISIBLE_DEVICES'] = '1' chaned to '0'

Thanks for helping to unblock the others. :)
