### ISSUE TITLE
Is there python 3 version demo?

### ISSUE THREAD

**Issue by RuoyuChen10** [fuy34/superpixel_fcn#46]
Thanks for your excellent work, I want if there any code support Python3? Thank you.

**Comment by RbtJhs** [comment]
If I remember correctly, you just need to replace the imread and imsave in ln 7&8 with, for instance, 'from skimage.io import imread, imsave'

**Comment by RuoyuChen10** [comment]
> If I remember correctly, you just need to replace the imread and imsave in ln 7&8 with, for instance, 'from skimage.io import imread, imsave'

Thanks! I will try it.
