### ISSUE TITLE
About the Prerequisites

### ISSUE THREAD

**Issue by tomoohive** [fuy34/superpixel_fcn#9]
I would like to try Superpixel FCN, but I could not construct the environment to execute.
I used nvidia-docker to build the environment of python2.7, Pytorch0.4.1, CUDA9, and Ubuntu16.04. However, I don't know what python packages I should install.
If it's not too much trouble, can you tell me your environment of python2.7 and installed packages?

Shown in the following my Dockerfile.

```
FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    git \
    python-dev \
    python-pip \
    python-setuptools \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install torch==0.4.1 \
    cython \
    numpy==1.16.6 \
    pillow==4.3.0 \
    PyWavelets==1.0.3 \
    networkx==2.2 \
    matplotlib==2.1.2 \
    scipy==1.2.3 \
    scikit-image==0.14.1

RUN git clone https://github.com/fuy34/superpixel_fcn.git

RUN cd ./superpixel_fcn/third_party/cython/ && python setup.py install --user
```

**Comment by fuy34** [comment]
Hi, 

I am sorry that I have updated the machine for my current project and cannot remember what exactly packages I was using. But I do not think the exact packages will have a big influence on the result, especially if you are using the same PyTorch version.  Do you meet any trouble to reproduce the result? 

Thanks.

**Comment by fuy34** [comment]
Closed for inactivity
